# Generated by Django 3.2.7 on 2021-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
