# Generated by Django 3.2.7 on 2021-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20210908_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Pork', 'Pork'), ('Duck', 'Duck')], default='food', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.FloatField(default=16.0),
        ),
    ]
