# Generated by Django 3.2.7 on 2021-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
