# Generated by Django 3.2.7 on 2021-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_rename_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Food',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderID',
            field=models.IntegerField(),
        ),
    ]
