# Generated by Django 3.2.7 on 2021-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20210922_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payType', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default='Card', max_length=20)),
                ('orderContent', models.CharField(max_length=999)),
            ],
        ),
    ]
