# Generated by Django 3.2.7 on 2021-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='itemAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
