# Generated by Django 3.2.7 on 2021-09-23 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0012_auto_20210923_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
